// Generated by LiveScript 1.3.1
(function(){
  var margin, height, width, textBlockWidth, max, min, stockInfo, stockGraph, intializeStockInfo, showStockPrice, data;
  margin = {
    top: 40,
    right: 80,
    bottom: 40,
    left: 80
  };
  height = 500 - margin.left - margin.right;
  width = 960 - margin.top - margin.right;
  textBlockWidth = width / 8;
  max = function(v1, v2){
    return v1 > v2 ? v1 : v2;
  };
  min = function(v1, v2){
    return v1 < v2 ? v1 : v2;
  };
  stockInfo = d3.select('.stock-graph').append('svg').attr("width", width + margin.left + margin.right).attr("height", 50).attr('class', 'stock-info');
  stockGraph = d3.select('.stock-graph').append('svg').attr("width", width + margin.left + margin.right).attr("height", height + margin.top + margin.bottom).attr('class', 'graph');
  intializeStockInfo = function(textSvg){
    textSvg.append('text').attr('class', 'text-info').attr('x', margin.left).attr('y', 30).text('Open:');
    textSvg.append('text').attr('class', 'open').attr('x', margin.left + 1 * textBlockWidth).attr('y', 30);
    textSvg.append('text').attr('class', 'text-info').attr('x', margin.left + 2 * textBlockWidth).attr('y', 30).text('High:');
    textSvg.append('text').attr('class', 'high').attr('x', margin.left + 3 * textBlockWidth).attr('y', 30);
    textSvg.append('text').attr('class', 'text-info').attr('x', margin.left + 4 * textBlockWidth).attr('y', 30).text('Low:');
    textSvg.append('text').attr('class', 'low').attr('x', margin.left + 5 * textBlockWidth).attr('y', 30);
    textSvg.append('text').attr('class', 'text-info').attr('x', margin.left + 6 * textBlockWidth).attr('y', 30).text('Close:');
    return textSvg.append('text').attr('class', 'close').attr('x', margin.left + 7 * textBlockWidth).attr('y', 30);
  };
  showStockPrice = function(d, textSvg){
    var color;
    color = d.open < d.close ? 'red' : 'green';
    textSvg.select('text.open').attr('fill', color).text(d.open);
    textSvg.select('text.high').attr('fill', color).text(d.high);
    textSvg.select('text.low').attr('fill', color).text(d.low);
    return textSvg.select('text.close').attr('fill', color).text(d.close);
  };
  intializeStockInfo(stockInfo);
  data = d3.csv('./test.csv', function(error, data){
    var parseDate, maxDate, minDate, minPrice, maxPrice, scaleX, scaleY, axisX, axisY;
    parseDate = d3.time.format('%d-%b-%y').parse;
    data = data.slice(0, 60).map(function(d){
      return {
        date: parseDate(d.Date),
        open: +d.Open,
        high: +d.High,
        low: +d.Low,
        close: +d.Close,
        volume: +d.Volume
      };
    });
    console.log(data);
    maxDate = d3.max(data, function(d){
      return d.date;
    });
    minDate = d3.min(data, function(d){
      return d.date;
    });
    minPrice = d3.min(data, function(d){
      return d.low;
    });
    maxPrice = d3.max(data, function(d){
      return d.high;
    });
    console.log(maxDate + '\n' + minDate);
    scaleX = d3.time.scale().range([0, width]).domain([minDate, maxDate]);
    scaleY = d3.scale.linear().range([height, 0]).domain([minPrice, maxPrice]);
    axisX = d3.svg.axis().scale(scaleX).ticks(10).tickFormat(d3.time.format('%m/%d')).orient('bottom');
    axisY = d3.svg.axis().scale(scaleY).orient('right');
    stockGraph.append('g').attr({
      'transform': 'translate(' + margin.left + ',' + (height + margin.top) + ')'
    }).attr('class', 'axis x').call(axisX);
    stockGraph.append('g').attr({
      'transform': 'translate(' + (width + margin.left) + ',' + margin.top + ')'
    }).attr('class', 'axis y').call(axisY);
    stockGraph.selectAll('line.ticks').data(scaleX.ticks()).enter().append('line').attr('x1', function(d){
      return margin.left + scaleX(new Date(d.toString()));
    }).attr('x2', function(d){
      return margin.left + scaleX(new Date(d.toString()));
    }).attr('y1', margin.top).attr('y2', margin.top + height).attr('stroke', '#ccc');
    stockGraph.selectAll('line.ticks').data(scaleY.ticks()).enter().append('line').attr('x1', margin.left).attr('x2', margin.left + width).attr('y1', function(d){
      return margin.top + scaleY(d);
    }).attr('y2', function(d){
      return margin.top + scaleY(d);
    }).attr('stroke', '#ccc');
    stockGraph.selectAll('rect').data(data).enter().append('rect').attr('x', function(d){
      var offset;
      offset = 0.25 * width / data.length;
      return margin.left - offset + scaleX(new Date(d.date));
    }).attr('y', function(d){
      var rectHeight;
      rectHeight = max(d.open, d.close);
      return margin.top + scaleY(rectHeight);
    }).attr('width', 0.5 * width / data.length).attr('height', function(d){
      var start, end;
      start = scaleY(min(d.open, d.close));
      end = scaleY(max(d.open, d.close));
      return start - end;
    }).on('mouseover', function(d){
      return showStockPrice(d, stockInfo);
    }).attr('fill', function(d){
      return d.open > d.close ? 'green' : 'red';
    });
    return stockGraph.selectAll('line.stem').data(data).enter().append('line').attr('x1', function(d){
      return margin.left + scaleX(new Date(d.date));
    }).attr('x2', function(d){
      return margin.left + scaleX(new Date(d.date));
    }).attr('y1', function(d){
      return margin.top + scaleY(d.high);
    }).attr('y2', function(d){
      return margin.top + scaleY(d.low);
    }).attr('stroke', function(d){
      return d.open > d.close ? 'green' : 'red';
    });
  });
}).call(this);
