// Generated by LiveScript 1.3.1
(function(){
  var margin, height, width, max, min, stockGraph, data;
  margin = {
    top: 80,
    right: 80,
    bottom: 80,
    left: 80
  };
  height = 500 - margin.left - margin.right;
  width = 960 - margin.top - margin.right;
  max = function(v1, v2){
    return v1 > v2 ? v1 : v2;
  };
  min = function(v1, v2){
    return v1 < v2 ? v1 : v2;
  };
  stockGraph = d3.select('.stock-graph').append('svg').attr("width", width + margin.left + margin.right).attr("height", height + margin.top + margin.bottom).attr('class', 'graph');
  data = d3.csv('./test.csv', function(error, data){
    var parseDate, maxDate, minDate, minPrice, maxPrice, scaleX, scaleY, axisX, axisY;
    parseDate = d3.time.format('%d-%b-%y').parse;
    data = data.slice(0, 60).map(function(d){
      return {
        date: parseDate(d.Date),
        open: +d.Open,
        high: +d.High,
        low: +d.Low,
        close: +d.Close,
        volume: +d.Volume
      };
    });
    console.log(data);
    maxDate = d3.max(data, function(d){
      return d.date;
    });
    minDate = d3.min(data, function(d){
      return d.date;
    });
    minPrice = d3.min(data, function(d){
      return d.low;
    });
    maxPrice = d3.max(data, function(d){
      return d.high;
    });
    console.log(maxDate + '\n' + minDate);
    scaleX = d3.time.scale().range([0, width]).domain([minDate, maxDate]);
    scaleY = d3.scale.linear().range([height, 0]).domain([minPrice, maxPrice]);
    axisX = d3.svg.axis().scale(scaleX).ticks(d3.time.days, 5).tickFormat(d3.time.format('%m/%d')).orient('bottom');
    axisY = d3.svg.axis().scale(scaleY).orient('right');
    stockGraph.append('g').attr({
      'transform': 'translate(' + margin.left + ',' + (height + margin.top) + ')'
    }).attr('class', 'axis x').call(axisX);
    stockGraph.append('g').attr({
      'transform': 'translate(' + (width + margin.left) + ',' + margin.top + ')'
    }).attr('class', 'axis y').call(axisY);
    stockGraph.selectAll('rect').data(data).enter().append('rect').attr('x', function(d){
      var offset;
      offset = 0.25 * width / data.length;
      return margin.left - offset + scaleX(new Date(d.date));
    }).attr('y', function(d){
      var rectHeight;
      rectHeight = max(d.open, d.close);
      return margin.top + scaleY(rectHeight);
    }).attr('width', 0.5 * width / data.length).attr('height', function(d){
      var start, end;
      start = scaleY(min(d.open, d.close));
      end = scaleY(max(d.open, d.close));
      return start - end;
    }).attr('fill', function(d){
      return d.open > d.close ? 'green' : 'red';
    });
    return stockGraph.selectAll('line.stem').data(data).enter().append('line').attr('x1', function(d){
      return margin.left + scaleX(new Date(d.date));
    }).attr('x2', function(d){
      return margin.left + scaleX(new Date(d.date));
    }).attr('y1', function(d){
      return margin.top + scaleY(d.high);
    }).attr('y2', function(d){
      return margin.top + scaleY(d.low);
    }).attr('stroke', function(d){
      return d.open > d.close ? 'green' : 'red';
    });
  });
}).call(this);
